import {state,save,load} from './store.js';
import {regions,regionById} from './config.js';
import {$,escapeHtml as esc,openModal,toast} from './ui.js';
import {countries,createLocationPicker} from './picker.js';
const regionAliases={...Object.fromEntries(regions.flatMap(r=>[[r.id,r.id],[r.name,r.id]])),亚洲:'Asia',欧洲:'Europe',北美洲:'North America',南美洲:'South America',非洲:'Africa',大洋洲:'Oceania'};
const imageRE=/\.(jpe?g|png|webp|avif)$/i;
const readFile=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error(`Unable to read ${file.name}`));reader.readAsDataURL(file);});
const newItem=()=>({id:crypto.randomUUID(),continent:'Asia',country:'',city:'',title:'Untitled project',year:null,area:null,lat:null,lon:null,description:'',photos:[],cover:null});
const optionalNumber=value=>value==null||value===''?null:Number(value);
export function createEditor({onOpen,onClose}){
  let draft=null,dirty=false,filter='',search='',busy=false,photoTarget=null,removed=[];
  const picker=createLocationPicker((id,lat,lon)=>{const item=draft.find(i=>i.id===id);Object.assign(item,{lat,lon,locationNote:'Position confirmed'});markDirty();renderRows();});
  $('#country-list').innerHTML=countries.map(c=>`<option value="${esc(c.name)}">${esc(c.en)}</option>`).join('');
  function markDirty(){dirty=true;$('#save-status').textContent='Unsaved changes';$('#save-cases').disabled=false;$('#reload-folder').disabled=true;$('#reload-folder').title='Save your changes before reloading';$('#editor-message').textContent='';}
  function markClean(){dirty=false;$('#save-status').textContent='All changes saved';$('#save-cases').disabled=true;$('#reload-folder').disabled=false;$('#reload-folder').title='';}
  function input(item,field,label,type='text',extra=''){return `<input data-field="${field}" aria-label="${label} ${esc(item.id)}" type="${type}" value="${esc(item[field])}" ${extra}>`;}
  function renderRows(){
    const visible=draft.filter(i=>!i.archived&&(!filter||i.continent===filter)&&(!search||[i.title,i.country,i.city].some(v=>v?.toLowerCase().includes(search))));
    $('#editor-rows').innerHTML=visible.map(item=>`<tr data-id="${esc(item.id)}"><td><div class="table-identity"><button class="cover-button" data-edit="photos" aria-label="Add photos to ${esc(item.title)}">${item.cover?`<img src="${esc(item.cover)}" alt="${esc(item.title)} cover">`:'＋'}</button><div>${input(item,'title','Project title','text','required maxlength="160"')}<small>${esc(item.folder||'New project')}</small></div></div></td><td><select data-field="continent" aria-label="Continent ${esc(item.id)}">${regions.map(r=>`<option value="${r.id}" ${r.id===item.continent?'selected':''}>${r.name}</option>`).join('')}</select></td><td>${input(item,'country','Country','text','required list="country-list" maxlength="100"')}</td><td>${input(item,'city','City','text','maxlength="100"')}</td><td><button class="coordinate-button" data-edit="location" aria-label="Place pin for ${esc(item.title)}">${item.lat!=null&&item.lon!=null?`${item.lat.toFixed(3)}, ${item.lon.toFixed(3)}<small>${esc(item.locationNote?.toLowerCase().includes('reference')?'Reference · Adjust pin':'Pinned · Edit location')}</small>`:'＋ Place on map'}</button></td><td>${input(item,'year','Year','number','min="1900" max="2100" step="1" placeholder="—"')}</td><td>${input(item,'area','Area','number','min="0" step="any" placeholder="—"')}</td><td><button class="photo-count-button" data-edit="photos" aria-label="Add photos to ${esc(item.title)}">${item.photos.length} photos +</button></td><td><button class="delete-button" data-edit="remove" aria-label="Remove ${esc(item.title)}" title="Remove from the atlas. Original photos are retained.">×</button></td></tr>`).join('');
    if(window.atlasHost?.openProject)for(const row of $('#editor-rows').children){const button=document.createElement('button');button.className='text-button';button.dataset.openProject=row.dataset.id;button.textContent='编辑详情 ↗';row.querySelector('.table-identity small').replaceChildren(button);}
    if(window.atlasHost?.remote){$('#editor-rows').querySelectorAll('input').forEach(n=>n.readOnly=true);$('#editor-rows').querySelectorAll('select,[data-edit]').forEach(n=>n.disabled=true);$('#save-cases').hidden=true;$('#import-folder').hidden=true;}
    $('#editor-empty').hidden=visible.length>0;$('#library-count').textContent=`${visible.length} projects`;$('#folder-path').textContent=state.folder;
  }
  function renderFilters(){ $('#editor-regions').innerHTML=[{id:'',name:'All projects'},...regions].map(r=>`<button data-filter="${r.id}" aria-pressed="${filter===r.id}">${r.name}</button>`).join(''); }
  $('#editor-regions').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;renderFilters();renderRows();};
  $('#case-search').oninput=e=>{search=e.target.value.trim().toLowerCase();renderRows();};
  $('#editor-rows').addEventListener('input',e=>{const field=e.target.dataset.field;if(!field)return;const item=draft.find(i=>i.id===e.target.closest('tr').dataset.id);item[field]=['year','area'].includes(field)?optionalNumber(e.target.value):e.target.value;markDirty();});
  $('#editor-rows').addEventListener('change',e=>{const field=e.target.dataset.field;if(!field)return;const item=draft.find(i=>i.id===e.target.closest('tr').dataset.id);if(field==='country'){const match=countries.find(c=>c.name===item.country||c.en.toLowerCase()===item.country.toLowerCase());if(match&&regionById[match.continent])item.continent=match.continent;item.lat=null;item.lon=null;item.locationNote='';renderRows();}if(field==='continent')renderRows();});
  $('#editor-rows').onclick=e=>{const b=e.target.closest('[data-edit]');if(!b||busy)return;const item=draft.find(i=>i.id===b.closest('tr').dataset.id);if(b.dataset.edit==='location')picker.open(item);if(b.dataset.edit==='photos'){photoTarget=item.id;$('#photo-input').click();}if(b.dataset.edit==='remove'){item.archived=true;removed.push(item.id);markDirty();renderRows();$('#editor-message').replaceChildren(document.createTextNode(`Removed ${item.title} from the atlas. Original photos are retained. `));const undo=document.createElement('button');undo.className='text-button';undo.textContent='Undo';undo.onclick=()=>{removed.forEach(id=>{const i=draft.find(x=>x.id===id);if(i)i.archived=false;});removed=[];renderRows();$('#editor-message').textContent='';};$('#editor-message').append(undo);}};
  async function openProject(id){
    if(busy)return;
    try{setBusy(true);if(dirty){await save(draft.filter(i=>!i.archived));markClean();}window.atlasHost.openProject(id);}
    catch(error){$('#editor-message').textContent=error.message;}finally{setBusy(false);}
  }
  $('#add-case').onclick=()=>{if(busy)return;if(window.atlasHost?.openProject)return openProject();const item=newItem();item.continent=filter||'Asia';draft.unshift(item);search='';$('#case-search').value='';markDirty();renderRows();$('#editor-rows input').focus();};
  $('#editor-rows').addEventListener('click',event=>{const target=event.target.closest('[data-open-project]');if(target)openProject(target.dataset.openProject);});
  async function uploads(files){const valid=files.filter(f=>imageRE.test(f.name));if(valid.some(f=>f.size>20*1024*1024))throw new Error('Each photo must be smaller than 20 MB.');if(valid.reduce((sum,f)=>sum+f.size,0)>65*1024*1024)throw new Error('Import photos in batches of up to 65 MB.');return Promise.all(valid.map(async file=>({name:file.name,data:await readFile(file)})));}
  function setBusy(value,label='Saving…'){busy=value;$('#save-cases').disabled=value||!dirty;$('#save-cases').textContent=value?label:'Save changes ↗';$('#import-folder').disabled=value;$('#add-case').disabled=value;$('#editor-rows').inert=value;}
  $('#photo-input').onchange=async e=>{try{setBusy(true,'Reading photos…');const item=draft.find(i=>i.id===photoTarget);const added=await uploads([...e.target.files]);item.uploads=[...(item.uploads||[]),...added];item.photos.push(...added.map(f=>f.data));item.cover ||=added[0]?.data;markDirty();renderRows();}catch(err){$('#editor-message').textContent=err.message;}finally{e.target.value='';setBusy(false);}};
  $('#import-folder').onclick=()=>$('#folder-input').click();
  $('#folder-input').onchange=async e=>{
    try{setBusy(true,'Reading folder…');const files=[...e.target.files];if(files.reduce((sum,f)=>sum+f.size,0)>65*1024*1024)throw new Error('Import files in batches of up to 65 MB.');const groups=new Map();
      for(const file of files){if(!imageRE.test(file.name)&&file.name!=='case.json')continue;const parts=file.webkitRelativePath.split('/');parts.pop();const folder=parts.join('/');if(!groups.has(folder))groups.set(folder,[]);groups.get(folder).push(file);}
      const imported=[],warnings=[];
      for(const [folder,group]of groups){const metadata=group.find(f=>f.name==='case.json');let data={};if(metadata){try{data=JSON.parse(await metadata.text());}catch{warnings.push(folder+': Unable to read project details.');}}
        const parts=folder.split('/'),regionIndex=parts.findIndex(p=>regionAliases[p]);const item=newItem();item.continent=regionAliases[data.continent]||regionAliases[parts[regionIndex]]||filter||'Asia';item.country=data.country||((regionIndex>=0&&parts.length>regionIndex+2)?parts[regionIndex+1]:'');item.title=data.title||parts.at(-1);item.city=data.city||'';item.description=data.description||'';for(const field of ['year','area','lat','lon'])item[field]=optionalNumber(data[field]);item.uploads=await uploads(group);item.photos=item.uploads.map(f=>f.data);item.cover=item.uploads.find(f=>f.name===data.cover)?.data||item.photos[0]||null;
        if(item.uploads.length||metadata)imported.push(item);
      }
      if(!imported.length)throw new Error('No photos or case.json found in this folder.');draft.unshift(...imported);filter='';search='';$('#case-search').value='';markDirty();renderFilters();renderRows();$('#editor-message').textContent=warnings.join('; ');$('#save-status').textContent=`${imported.length} projects imported. Save to add them to the atlas.`;
    }catch(err){$('#editor-message').textContent=err.message;}finally{e.target.value='';setBusy(false);}
  };
  $('#save-cases').onclick=async()=>{
    const invalid=draft.find(i=>!i.archived&&(!i.title.trim()||!i.country.trim()||(i.year!==null&&(!Number.isInteger(i.year)||i.year<1900||i.year>2100))||(i.area!==null&&(!Number.isFinite(i.area)||i.area<0))||((i.lat===null)!==(i.lon===null))||(i.lat!==null&&(!Number.isFinite(i.lat)||Math.abs(i.lat)>90||!Number.isFinite(i.lon)||Math.abs(i.lon)>180))));
    if(invalid){filter='';search='';$('#case-search').value='';renderFilters();renderRows();$('#editor-message').textContent=`${invalid.title||'Untitled project'}: Enter a title and country, and check the year, area and coordinates.`;const row=[...$('#editor-rows').children].find(r=>r.dataset.id===invalid.id);row?.classList.add('row-error');row?.scrollIntoView({block:'nearest'});row?.querySelector('input:invalid')?.focus();return;}
    try{setBusy(true);await save(draft.filter(i=>!i.archived||i.folder));draft=structuredClone(state.items);removed=[];markClean();renderRows();$('#editor-message').textContent='';toast('Changes saved. The atlas is up to date.');}catch(err){$('#editor-message').textContent=err.message;$('#save-status').textContent='Save failed. Your changes are still here.';}finally{setBusy(false);}
  };
  $('#reload-folder').onclick=async()=>{if(dirty||busy)return;try{setBusy(true,'Loading…');await load();draft=structuredClone(state.items);renderRows();toast('Project folder reloaded.');}catch(err){$('#editor-message').textContent=err.message;}finally{setBusy(false);}};
  $('#export-data').onclick=()=>{const result={version:1,cases:draft.filter(i=>!i.archived).map(({uploads,photos,cover,...item})=>({...item,photos:photos.filter(p=>!p.startsWith('data:')),cover:cover?.startsWith('data:')?null:cover}))};const blob=new Blob([JSON.stringify(result,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='project-data.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Project data exported.');};
  $('#editor').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('#editor').addEventListener('close',()=>{if(dirty)toast('Your draft is retained. Reopen the editor to continue.');onClose();});
  window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
  return {open(){if(!dirty){draft=structuredClone(state.items);markClean();}renderFilters();renderRows();$('#editor-message').textContent=state.warnings.join('; ');openModal('editor');onOpen();}};
}
